name: ${ENV_PROJECT_NAME}

services:
  app:
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}:latest
    env_file:
      - .env
    volumes:
      - ./src/filter_config.toml:/app/src/filter_config.toml
