name: ${ENV_PROJECT_NAME}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENV_MODE}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
